import { Heart, Star, Gift, Sun, Coffee, Utensils, Camera } from "lucide-react";

export const adventuresList = {
    en: [
        { text: "The way you say my name like it means something", icon: Heart },
        { text: "Late night calls that somehow lasted until sunrise", icon: Sun },
        { text: "Your laugh, even through a bad connection", icon: Heart },
        { text: "The comfort of being heard, no matter the distance", icon: Heart },
        { text: "Every 'good morning' text before mine", icon: Star },
        { text: "The quiet, unspoken trust between us", icon: Heart },
        { text: "Cooking the same recipe, miles apart", icon: Utensils },
        { text: "The blood-red portrait, still hanging where I can see it", icon: Camera },
        { text: "Long calls about absolutely nothing", icon: Coffee },
        { text: "Your voice, the last thing I hear before sleep", icon: Star },
        { text: "The nervous excitement before every visit", icon: Heart },
        { text: "The way you remember things I've forgotten I said", icon: Gift },
        { text: "Your small acts of care, never asked for", icon: Gift },
        { text: "The safety of your presence, even from far away", icon: Heart },
        { text: "Just being together, without needing a reason", icon: Heart },
        { text: "Renewing my promise to you, in my own heart, every single day", icon: Star },
    ],
    ta: [
        { text: "என் பெயரை நீ சொல்லும் விதம், அது ஏதோ அர்த்தமுள்ளதாக இருக்கிறது", icon: Heart },
        { text: "இரவு நேர அழைப்புகள், எப்படியோ சூரிய உதயம் வரை நீண்டது", icon: Sun },
        { text: "மோசமான நெட்வொர்க்கிலும் உன் சிரிப்பு", icon: Heart },
        { text: "தூரம் இருந்தாலும் கேட்கப்படுவதின் ஆறுதல்", icon: Heart },
        { text: "என்னுடையதற்கு முன்பே வரும் 'காலை வணக்கம்' மெசேஜ்", icon: Star },
        { text: "நம் இடையேயான அமைதியான, சொல்லாத நம்பிக்கை", icon: Heart },
        { text: "மைல்கள் தள்ளி இருந்தும் ஒரே செய்முறையை சமைப்பது", icon: Utensils },
        { text: "இன்னும் என் சுவரில் தொங்கும் இரத்த-சிவப்பு உருவப்படம்", icon: Camera },
        { text: "எதுவுமில்லாத விஷயங்களைப் பற்றி நீண்ட அழைப்புகள்", icon: Coffee },
        { text: "தூங்குவதற்கு முன் நான் கேட்கும் உன் கடைசி குரல்", icon: Star },
        { text: "ஒவ்வொரு சந்திப்புக்கு முன்பும் இருந்த பதற்றமான உற்சாகம்", icon: Heart },
        { text: "நான் சொன்னதை நானே மறந்தும், நீ நினைவில் வைத்திருக்கும் விதம்", icon: Gift },
        { text: "கேட்காமலேயே நீ செய்யும் சிறிய அக்கறைகள்", icon: Gift },
        { text: "தூரத்திலிருந்தும் உன் இருப்பு தரும் பாதுகாப்பு", icon: Heart },
        { text: "எந்தக் காரணமும் இல்லாமல், சும்மா ஒன்றாக இருப்பது", icon: Heart },
        { text: "என் இதயத்தில், ஒவ்வொரு நாளும் உனக்கான என் வாக்குறுதியைப் புதுப்பிப்பது", icon: Star },
    ]
};
