export const content = {
    en: {
        question: "Will you be my Valentine?",
        subtext: "To my dearest Muhh (Ancy) 🍁",
        yes: "Absolutely Yes!",
        no: "No Way",
        accepted: "Forever and Always! ❤️",
        driver_text: "To my world, my everything... let's begin our ride.",
        cta: "Step Into Our Story",
        our_world: "Our World",
        dubai: "Dubai",
        tirunelveli: "India",
        dubai_label: "My Driver's Home 🇦🇪",
        tirunelveli_label: "Ancy's Home 🇮🇳",
        togetherness: "5+ Years of Togetherness",
        connected: "UAE & India connected by love.",
        distance_quote: "Distance means nothing when someone means everything.",
        start_journey: "Start Our Journey",
        continue_story: "Continue Our Story",
        memory_cube: "Memory Cube",
        cube_title: "A Cube of Memories",
        cube_desc: "Every side reveals a part of our 5-year story.",
        reasons_title: "100 Reasons Why",
        reasons_desc: "Swipe through some of the reasons you mean the world to me.",
        garden_title: "Zen Garden of Leaves",
        garden_desc: "Draw with your love to leave a trail of 🍁 maple memories.",
        soundtrack_instruction: "Tap the record to hear the melody of our 5-year journey.",
        reason_label: "Reason",
        of: "of",
        adventure_title: "Reunion Adventure List",
        adventure_desc: "Things we will do together, once distance is gone forever.",
        hearts_title: "Catch My Love",
        hearts_desc: "Tap the falling hearts to unlock sweet secrets.",
        ticker_title: "The Ticker of Forever",
        ticker_desc: "Every second since Jan 22, 2021, my heart has beat for you.",
        oracle_title: "",
        oracle_desc: "",
        oracle_instruction: "",
        oracle_subtitle: "",
        oracle_cta: "",
        oracle_usage: "",
        cube_muhh_emoji: "Muhh 🧸👑 🍁",
        letters_title: "Enveloped Letters",
        letters_desc: "Personal letters from my heart to yours, waiting to be opened.",
        capsule_title: "Our Future Capsule",
        capsule_desc: "A promise for the days to come. Locked until our reunion.",
        starmap_title: "The Sky We Share",
        starmap_desc: "Different lands, same stars. Our connection is written above.",
        hug_title: "The Global Hug",
        hug_desc: "Two hearts, two cities, one pulse. Hold to send a hug across the sea.",
        poetry_title: "Tamil Kavithai",
        poetry_desc: "The beauty of our love, told through the richness of our language.",
        char_title: "Driver & Muhh",
        char_desc: "5 years, 2 countries, 1 beautiful story of ours.",
        milestone_title: "5 Years of Us",
        milestone_desc: "Looking back at the milestones that made us who we are today.",
        anniversary_title: "The Day We First Kissed",
        anniversary_desc: "A moment frozen in time. March 25th, the day our hearts met.",
        date_title: "Virtual Date Generator",
        date_desc: "Click to plan our next virtual date night.",
        credits_title: "The Credits of Love",
        credits_desc: "Thank you for being my everything. To many more years!",
        years: "Years",
        months: "Months",
        days: "Days",
        hours: "Hours",
        minutes: "Minutes",
        seconds: "Seconds",
        loyola_days: "Loyola Days",
        ego_title: "1000/100 EGO",
        ego_desc: "Where it all began... Two stubborn hearts vs the world.",
        bus_chase: "The Great Bus Chase",
        bus_desc: "Geo chasing the college bus just to see Ancy 🚌💨",
        panagudi_wait: "Panagudi Evenings",
        panagudi_desc: "Waiting at the bus stop for her every single day.",
        insta_handle: "Personal Bond 🧸",
        blood_art_title: "The Blood Art",
        blood_art_desc: "A piece of my heart, drawn from my very soul to show you my love.",
        cta_cube: "Continue our Journey",
        cta_reasons: "Explore Our Garden",
        cta_garden: "Plan Our Adventures",
        cta_adventure: "Play for My Heart",
        cta_hearts: "Watch Our Time Flow",
        cta_ticker: "Open My Letters",
        cta_oracle: "",
        cta_letters: "Seal Our Future",
        cta_capsule: "Look at the Stars",
        cta_starmap: "Send a Global Hug",
        cta_hug: "Read Our Poetry",
        cta_poetry: "Meet the Characters",
        cta_characters: "View Our Milestones",
        cta_milestones: "Recall the Anniversary",
        cta_anniversary: "Schedule a Special Date",
        cta_dategen: "To the Grand Finale",
    },
    ta: {
        question: "நீ என் காதலியாக இருப்பாயா?",
        subtext: "என் அன்பான முஹ் (Ancy) 🍁",
        yes: "நிச்சயமாக!",
        no: "இல்லை",
        accepted: "என்றும் உன்னுடையவன்! ❤️",
        driver_text: "என் உலகமே, என் எல்லாமே... நமது பயணத்தைத் தொடங்குவோம்.",
        cta: "நமது கதையைக் காணுங்கள்",
        our_world: "நமது உலகம்",
        dubai: "துபாய்",
        tirunelveli: "இந்தியா",
        dubai_label: "எனது டிரைவரின் இல்லம் 🇦🇪",
        tirunelveli_label: "Ancy-யின் இல்லம் 🇮🇳",
        togetherness: "5+ ஆண்டுகள் ஒன்றாக",
        connected: "காதலால் இணைக்கப்பட்ட ஐக்கிய அரபு அமீரகம் & இந்தியா.",
        distance_quote: "யாரோ ஒருவர் எல்லாவற்றையும் குறிக்கும் போது தூரம் எதையும் குறிக்காது.",
        start_journey: "நமது பயணத்தைத் தொடங்குங்கள்",
        continue_story: "நமது கதையைத் தொடரவும்",
        memory_cube: "நினைவு கன சதுரம்",
        cube_title: "நினைவுகளின் கன சதுரம்",
        cube_desc: "ஒவ்வொரு பக்கமும் நமது 5 ஆண்டு கதையின் ஒரு பகுதியை வெளிப்படுத்துகிறது.",
        reasons_title: "100 காரணங்கள்",
        reasons_desc: "ஸ்வைப் செய்வதன் மூலம் நான் உங்களை விரும்புவதற்கான காரணங்களைக் காணலாம்.",
        garden_title: "இலையுதிர் கால தோட்டம்",
        garden_desc: "நமது அன்பால் 🍁 இலைகளின் தடத்தை உருவாக்க இங்கே வரையவும்.",
        soundtrack_title: "நமது இசைப்பயணம்",
        soundtrack_desc: "ஆண்டுகள் கடந்தும் சுழலும் நமது இதயங்களின் தாளம்.",
        soundtrack_instruction: "நமது 5 ஆண்டு பயணத்தின் இசையைக் கேட்க வினைலினைத் தட்டவும்.",
        reason_label: "காரணம்",
        of: "இல்",
        adventure_title: "மீண்டும் சந்திக்கும் சாகசப் பட்டியல்",
        adventure_desc: "தூரம் என்றென்றும் மறைந்தவுடன் நாம் செய்யப்போகும் செயல்கள்.",
        hearts_title: "என் அன்பைப் பிடி",
        hearts_desc: "இனிமையான ரகசியங்களைத் திறக்க விழும் இதயங்களைத் தட்டவும்.",
        ticker_title: "என்றென்றும் தொடரும் கணக்கு",
        ticker_desc: "ஜனவரி 22, 2021 முதல் ஒவ்வொரு நொடியும் என் இதயம் உனக்காகத் துடிக்கிறது.",
        oracle_title: "",
        oracle_desc: "",
        oracle_instruction: "",
        oracle_subtitle: "",
        oracle_cta: "",
        oracle_usage: "",
        cube_muhh_emoji: "Muhh 🧸👑 🍁",
        letters_title: "உறை கடிதங்கள்",
        letters_desc: "உங்களுக்காக என் இதயத்திலிருந்து வரும் தனிப்பட்ட கடிதங்கள்.",
        capsule_title: "நமது எதிர்கால காப்ஸ்யூல்",
        capsule_desc: "வரவிருக்கும் நாட்களுக்கான வாக்குறுதி. நாம் மீண்டும் சந்திக்கும் வரை இது பூட்டப்பட்டிருக்கும்.",
        starmap_title: "நாம் பகிரும் வானம்",
        starmap_desc: "வேறு நிலங்கள், அதே நட்சத்திரங்கள். நமது இணைப்பு மேலே எழுதப்பட்டுள்ளது.",
        soundtrack_custom_title: "நமது பாடலை மாற்றவும்",
        soundtrack_usage: "நமது சிறப்புப் பாடலை ஒலிக்க ஒரு YouTube அல்லது MP3 இணைப்பை உள்ளிடவும்.",
        custom_song_placeholder: "பாடல் இணைப்பை இங்கே ஒட்டவும்...",
        hug_title: "உலகளாவிய கட்டிப்பிடித்தல்",
        hug_desc: "இரண்டு இதயங்கள், இரண்டு நகரங்கள், ஒரு துடிப்பு. கடல் கடந்து ஓரு கட்டியணைப்பை அனுப்ப அழுத்திப் பிடிக்கவும்.",
        poetry_title: "தமிழ் கவிதை",
        poetry_desc: "நமது மொழியின் செழுமையின் மூலம் சொல்லப்படும் நமது காதலின் அழகு.",
        char_title: "டிரைவர் & முஹ்",
        char_desc: "5 ஆண்டுகள், 2 நாடுகள், நமது 1 அழகான கதை.",
        milestone_title: "நமது 5 ஆண்டுகள்",
        milestone_desc: "இன்று நாம் யார் என்பதை உருவாக்கிய மைல்கற்களைத் திரும்பிப் பார்க்கிறோம்.",
        anniversary_title: "நமது முதல் முத்தம்",
        anniversary_desc: "காலத்தால் உறைய வைக்கப்பட்ட ஒரு தருணம். மார்ச் 25, நமது இதயங்கள் சந்தித்த நாள்.",
        date_title: "மெய்நிகர் தேதி ஜெனரேட்டர்",
        date_desc: "நமது அடுத்த மெய்நிகர் தேதி இரவைத் திட்டமிட கிளிக் செய்யவும்.",
        credits_title: "காதல் வரவுகள்",
        credits_desc: "எனக்கு எல்லாவற்றிற்கும் நன்றி. இன்னும் பல ஆண்டுகளுக்கு!",
        years: "ஆண்டுகள்",
        months: "மாதங்கள்",
        days: "நாட்கள்",
        hours: "மணிநேரம்",
        minutes: "நிமிடங்கள்",
        seconds: "நொடிகள்",
        loyola_days: "லயோலா நாட்கள்",
        ego_title: "1000/100 ஈகோ",
        ego_desc: "எல்லாம் தொடங்கிய இடம்... உலகின் முன்னே இரண்டு பிடிவாத இதயங்கள்.",
        bus_chase: "பெரிய பேருந்து வேட்டை",
        bus_desc: "ஆன்சியைப் பார்க்க ஜியோ கல்லூரி பேருந்தைத் துரத்தினார் 🚌💨",
        panagudi_wait: "பணகுடி மாலைகள்",
        panagudi_desc: "ஒவ்வொரு நாளும் பேருந்து நிறுத்தத்தில் அவளுக்காகக் காத்திருக்கிறார்.",
        insta_handle: "Teddie queen 🧸",
        blood_art_title: "இரத்தக் கலை",
        blood_art_desc: "உன் மீதான என் காதலை வெளிப்படுத்த என் ஆன்மாவிலிருந்து வரையப்பட்ட ஒரு இதயம்.",
        cta_cube: "நமது தோட்டத்தை ஆராயுங்கள்",
        cta_reasons: "நமது தோட்டத்தை ஆராயுங்கள்",
        cta_garden: "நமது தாளத்தைக் கேளுங்கள்",
        cta_soundtrack: "நமது சாகசங்களைத் திட்டமிடுங்கள்",
        cta_adventure: "என் இதயத்திற்காக விளையாடுங்கள்",
        cta_hearts: "நமது நேர ஓட்டத்தைப் பாருங்கள்",
        cta_ticker: "ஆரக்கிளிடம் கேளுங்கள்",
        cta_letters: "நமது எதிர்காலத்தை உறுதிப்படுத்துங்கள்",
        cta_capsule: "நட்சத்திரங்களைப் பாருங்கள்",
        cta_starmap: "உலகளாவிய கட்டியணைப்பை அனுப்பவும்",
        cta_hug: "நமது கவிதையைப் படியுங்கள்",
        cta_poetry: "உருவங்களைச் சந்திக்கவும்",
        cta_characters: "நமது மைல்கற்களைப் பாருங்கள்",
        cta_milestones: "ஆண்டுவிழாவை நினைவு கூருங்கள்",
        cta_anniversary: "சிறப்புத் தேதியைத் திட்டமிடுங்கள்",
        cta_dategen: "பெரிய இறுதிப் பகுதிக்கு",
    },
};
