export const content = {
    en: {
        question: "You Are Always My Valentine",
        subtext: "To my dearest Muhh (Ancy) 🍁",
        accepted: "Forever and Always! ❤️",
        driver_text: "To my world, my everything... this ride was always meant for us.",
        cta: "Step Into Our Story",
        our_world: "Our World",
        dubai: "Dubai",
        tirunelveli: "India",
        dubai_label: "My Driver 🇦🇪",
        tirunelveli_label: "Ancy 🇮🇳",
        togetherness: "5+ Years of Togetherness",
        connected: "UAE & India connected by love.",
        distance_quote: "Distance means nothing when someone means everything.",
        start_journey: "Start Our Journey",
        continue_story: "Continue Our Story",
        memory_cube: "Memory Cube",
        cube_title: "A Cube of Memories",
        cube_desc: "Every side reveals a part of our 5-year story.",
        cube_face_heart: "Our Bond",
        cube_face_ring: "The Promise",
        cube_face_cap: "College Days",
        cube_face_car: "My Driver",
        cube_face_teddy: "Muhh's Teddy",
        cube_face_muhh: "Falling for You",
        cube_quote_heart: "Every heartbeat since 2021 has quietly belonged to you.",
        cube_quote_ring: "A promise isn't magic — it's choosing you, over and over.",
        cube_quote_cap: "Back in college, I never guessed you'd become my forever.",
        cube_quote_car: "Every road felt shorter with you sitting beside me.",
        cube_quote_teddy: "For the nights I couldn't hold you, I hoped this would.",
        cube_quote_muhh: "Like a leaf on the wind, I fell for you without trying.",
        reasons_title: "100 Reasons Why",
        reasons_desc: "Swipe through some of the reasons you mean the world to me.",
        reasons_milestone: "Another milestone unlocked — and I still haven't run out of reasons.",
        reasons_finale: "100 reasons... but really, there's no end to why I love you.",
        garden_title: "Zen Garden of Leaves",
        garden_desc: "Draw with your love to leave a trail of 🍁 maple memories.",
        garden_counter_label: "memories drawn together",
        garden_milestone: "Every leaf you draw is a memory we're planting together.",
        soundtrack_instruction: "Tap the record to hear the melody of our 5-year journey.",
        reason_label: "Reason",
        of: "of",
        adventure_title: "Moments I'll Carry With Me",
        adventure_desc: "Small things that mattered more than I ever said out loud.",
        adventure_recap: "Every one of these is a piece of her I still keep.",
        hearts_title: "Catch My Love",
        hearts_desc: "Tap the falling hearts to unlock sweet secrets.",
        hearts_milestone: "25 hearts caught — and I'd fall for you all over again.",
        ticker_title: "The Ticker of Forever",
        ticker_desc: "Every second since Jan 22, 2021, my heart has beat for you.",
        oracle_title: "",
        oracle_desc: "",
        oracle_instruction: "",
        oracle_subtitle: "",
        oracle_cta: "",
        oracle_usage: "",
        cube_muhh_emoji: "Muhh 🧸👑 🍁",
        letters_title: "Enveloped Letters",
        letters_desc: "Personal letters from my heart to yours, waiting to be opened.",
        capsule_title: "A Memory, Sealed",
        capsule_desc: "One of the moments I chose to keep forever, sealed here so I never forget.",
        capsule_tap_label: "Tap to Seal Forever",
        capsule_sealing_label: "Sealing This Memory",
        capsule_sealed_label: "Sealed with Love",
        capsule_promise_heading: "One I'll Always Keep",
        capsule_promise_label: "The memory I chose to keep:",
        capsule_fallback_quote: "Every moment still matters. Ours is a story worth remembering.",
        starmap_title: "The Sky We Share",
        starmap_desc: "Different lands, same stars. Our connection is written above.",
        hug_title: "The Global Hug",
        hug_desc: "Two hearts, two cities, one pulse. Hold to send a hug across the sea.",
        hug_long_press_label: "Long Press to Hug",
        hug_hugging_label: "Hugging Your Geo...",
        poetry_title: "Written For You",
        poetry_desc: "A few lines from my heart, in the language closest to yours.",
        char_title: "Driver & Muhh",
        char_desc: "5 years, 2 countries, 1 beautiful story of ours.",
        char_geo_caption: "A software developer in Dubai, forever her 'Driver'",
        char_ancy_caption: "The maple leaf who stole a driver's heart",
        char_joined_message: "In my heart, every road leads back to you.",
        milestone_title: "5 Years of Us",
        milestone_desc: "Looking back at the milestones that made us who we are today.",
        anniversary_title: "The Day We First Met",
        anniversary_desc: "Two strangers, one moment. January 22nd, the day our story began.",
        date_title: "Memory Roulette",
        date_desc: "Spin to relive one of our moments together.",
        credits_title: "The Credits of Love",
        credits_desc: "Thank you for being my everything. Every year of it still matters to me.",
        years: "Years",
        months: "Months",
        days: "Days",
        hours: "Hours",
        minutes: "Minutes",
        seconds: "Seconds",
        loyola_days: "Loyola Days",
        ego_title: "1000/100 EGO",
        ego_desc: "Where it all began... Two stubborn hearts vs the world.",
        bus_chase: "The Great Bus Chase",
        bus_desc: "Geo chasing the college bus just to see Ancy 🚌💨",
        panagudi_wait: "Panagudi Evenings",
        panagudi_desc: "Waiting at the bus stop for her every single day.",
        insta_handle: "Personal Bond 🧸",
        blood_art_title: "The Blood Art",
        blood_art_desc: "A piece of my heart, drawn from my very soul to show you my love.",
        cta_cube: "Continue our Journey",
        cta_reasons: "Explore Our Garden",
        cta_garden: "Plan Our Adventures",
        cta_adventure: "Play for My Heart",
        cta_hearts: "Watch Our Time Flow",
        cta_ticker: "Open My Letters",
        cta_oracle: "",
        cta_letters: "Seal These Memories",
        cta_capsule: "Look at the Stars",
        cta_starmap: "Send a Global Hug",
        cta_hug: "Read Our Poetry",
        cta_poetry: "Meet the Characters",
        poetry_tap_hint: "Tap a heart to reveal what's written inside",
        poetry_teaser_prefix: "A memory from",
        poetry_more_waiting: "There's more waiting, whenever you come back.",
        cta_characters: "View Our Milestones",
        cta_milestones: "Relive Our Anniversary",
        cta_anniversary: "Schedule a Special Date",
        cta_dategen: "To the Grand Finale",
    },
    ta: {
        question: "நீ எப்போதும் என் காதலி",
        subtext: "என் அன்பான முஹ் (Ancy) 🍁",
        accepted: "என்றும் உன்னுடையவன்! ❤️",
        driver_text: "என் உலகமே, என் எல்லாமே... இந்தப் பயணம் எப்போதும் நமக்காகவே இருந்தது.",
        cta: "நமது கதையைக் காணுங்கள்",
        our_world: "நமது உலகம்",
        dubai: "துபாய்",
        tirunelveli: "இந்தியா",
        dubai_label: "எனது டிரைவர் 🇦🇪",
        tirunelveli_label: "Ancy 🇮🇳",
        togetherness: "5+ ஆண்டுகள் ஒன்றாக",
        connected: "காதலால் இணைக்கப்பட்ட ஐக்கிய அரபு அமீரகம் & இந்தியா.",
        distance_quote: "யாரோ ஒருவர் எல்லாவற்றையும் குறிக்கும் போது தூரம் எதையும் குறிக்காது.",
        start_journey: "நமது பயணத்தைத் தொடங்குங்கள்",
        continue_story: "நமது கதையைத் தொடரவும்",
        memory_cube: "நினைவு கன சதுரம்",
        cube_title: "நினைவுகளின் கன சதுரம்",
        cube_desc: "ஒவ்வொரு பக்கமும் நமது 5 ஆண்டு கதையின் ஒரு பகுதியை வெளிப்படுத்துகிறது.",
        cube_face_heart: "நமது பிணைப்பு",
        cube_face_ring: "வாக்குறுதி",
        cube_face_cap: "கல்லூரி நாட்கள்",
        cube_face_car: "எனது டிரைவர்",
        cube_face_teddy: "Muhh-வின் கரடி பொம்மை",
        cube_face_muhh: "உன் காதலில் விழுந்தேன்",
        cube_quote_heart: "2021 முதல் ஒவ்வொரு இதயத் துடிப்பும் அமைதியாக உனக்குச் சொந்தமானது.",
        cube_quote_ring: "வாக்குறுதி என்பது மந்திரம் அல்ல — அது உன்னை மீண்டும் மீண்டும் தேர்ந்தெடுப்பது.",
        cube_quote_cap: "கல்லூரி நாட்களில், நீ என் என்றென்றைக்குமான துணையாவாய் என்று நான் நினைக்கவே இல்லை.",
        cube_quote_car: "நீ அருகில் இருந்தால் ஒவ்வொரு பயணமும் குறுகியதாக உணர்ந்தேன்.",
        cube_quote_teddy: "என்னால் உன்னைக் கட்டியணைக்க முடியாத இரவுகளுக்காக, இது அதைச் செய்யும் என நம்பினேன்.",
        cube_quote_muhh: "காற்றில் பறக்கும் ஓர் இலை போல, முயற்சியின்றி உன் காதலில் விழுந்தேன்.",
        reasons_title: "100 காரணங்கள்",
        reasons_desc: "ஸ்வைப் செய்வதன் மூலம் நான் உங்களை விரும்புவதற்கான காரணங்களைக் காணலாம்.",
        reasons_milestone: "இன்னொரு மைல்கல்லைத் தாண்டிவிட்டீர்கள் — இன்னும் காரணங்கள் தீரவில்லை.",
        reasons_finale: "100 காரணங்கள்... ஆனால் உண்மையில், நான் உன்னை நேசிப்பதற்கு முடிவே இல்லை.",
        garden_title: "இலையுதிர் கால தோட்டம்",
        garden_desc: "நமது அன்பால் 🍁 இலைகளின் தடத்தை உருவாக்க இங்கே வரையவும்.",
        garden_counter_label: "நினைவுகள் ஒன்றாக வரையப்பட்டன",
        garden_milestone: "நீங்கள் வரையும் ஒவ்வொரு இலையும் நாம் ஒன்றாக நடும் ஒரு நினைவே.",
        soundtrack_title: "நமது இசைப்பயணம்",
        soundtrack_desc: "ஆண்டுகள் கடந்தும் சுழலும் நமது இதயங்களின் தாளம்.",
        soundtrack_instruction: "நமது 5 ஆண்டு பயணத்தின் இசையைக் கேட்க வினைலினைத் தட்டவும்.",
        reason_label: "காரணம்",
        of: "இல்",
        adventure_title: "நான் சுமந்து செல்லும் தருணங்கள்",
        adventure_desc: "நான் ஒருபோதும் சொல்லாத, ஆனால் மிக முக்கியமான சிறிய விஷயங்கள்.",
        adventure_recap: "இவை ஒவ்வொன்றும் நான் இன்னும் வைத்திருக்கும் அவளின் ஒரு பகுதி.",
        hearts_title: "என் அன்பைப் பிடி",
        hearts_desc: "இனிமையான ரகசியங்களைத் திறக்க விழும் இதயங்களைத் தட்டவும்.",
        hearts_milestone: "25 இதயங்கள் பிடிக்கப்பட்டன — மீண்டும் உன் காதலில் விழுவேன்.",
        ticker_title: "என்றென்றும் தொடரும் கணக்கு",
        ticker_desc: "ஜனவரி 22, 2021 முதல் ஒவ்வொரு நொடியும் என் இதயம் உனக்காகத் துடிக்கிறது.",
        oracle_title: "",
        oracle_desc: "",
        oracle_instruction: "",
        oracle_subtitle: "",
        oracle_cta: "",
        oracle_usage: "",
        cube_muhh_emoji: "Muhh 🧸👑 🍁",
        letters_title: "உறை கடிதங்கள்",
        letters_desc: "உங்களுக்காக என் இதயத்திலிருந்து வரும் தனிப்பட்ட கடிதங்கள்.",
        capsule_title: "ஒரு நினைவு, முத்திரையிடப்பட்டது",
        capsule_desc: "நான் எப்போதும் மறக்காமல் இருக்க தேர்ந்தெடுத்த ஒரு தருணம், இங்கே முத்திரையிடப்பட்டுள்ளது.",
        capsule_tap_label: "என்றென்றும் முத்திரையிட தட்டவும்",
        capsule_sealing_label: "இந்த நினைவை முத்திரையிடுகிறேன்",
        capsule_sealed_label: "அன்புடன் முத்திரையிடப்பட்டது",
        capsule_promise_heading: "எப்போதும் நான் வைத்திருப்பது",
        capsule_promise_label: "நான் தேர்ந்தெடுத்த நினைவு:",
        capsule_fallback_quote: "ஒவ்வொரு தருணமும் இன்னும் அர்த்தமுள்ளதாக இருக்கிறது. நம்முடையது நினைவில் வைக்கத் தகுந்த ஒரு கதை.",
        starmap_title: "நாம் பகிரும் வானம்",
        starmap_desc: "வேறு நிலங்கள், அதே நட்சத்திரங்கள். நமது இணைப்பு மேலே எழுதப்பட்டுள்ளது.",
        soundtrack_custom_title: "நமது பாடலை மாற்றவும்",
        soundtrack_usage: "நமது சிறப்புப் பாடலை ஒலிக்க ஒரு YouTube அல்லது MP3 இணைப்பை உள்ளிடவும்.",
        custom_song_placeholder: "பாடல் இணைப்பை இங்கே ஒட்டவும்...",
        hug_title: "உலகளாவிய கட்டிப்பிடித்தல்",
        hug_desc: "இரண்டு இதயங்கள், இரண்டு நகரங்கள், ஒரு துடிப்பு. கடல் கடந்து ஓரு கட்டியணைப்பை அனுப்ப அழுத்திப் பிடிக்கவும்.",
        hug_long_press_label: "கட்டிப்பிடிக்க அழுத்திப் பிடி",
        hug_hugging_label: "உன் ஜியோவை கட்டிப்பிடிக்கிறேன்...",
        poetry_title: "உனக்காக எழுதியவை",
        poetry_desc: "என் இதயத்திலிருந்து சில வரிகள், உனக்கு மிக நெருக்கமான மொழியில்.",
        char_title: "டிரைவர் & முஹ்",
        char_desc: "5 ஆண்டுகள், 2 நாடுகள், நமது 1 அழகான கதை.",
        char_geo_caption: "துபாயில் ஒரு மென்பொருள் டெவலப்பர், எப்போதும் அவளுடைய 'டிரைவர்'",
        char_ancy_caption: "ஒரு டிரைவரின் இதயத்தைத் திருடிய இலையுதிர் இலை",
        char_joined_message: "என் இதயத்தில், ஒவ்வொரு பாதையும் உன்னிடமே திரும்பும்.",
        milestone_title: "நமது 5 ஆண்டுகள்",
        milestone_desc: "இன்று நாம் யார் என்பதை உருவாக்கிய மைல்கற்களைத் திரும்பிப் பார்க்கிறோம்.",
        anniversary_title: "நாம் முதலில் சந்தித்த நாள்",
        anniversary_desc: "இரு அந்நியர்கள், ஒரு தருணம். ஜனவரி 22, நமது கதை தொடங்கிய நாள்.",
        date_title: "நினைவு உருளை",
        date_desc: "நமது தருணங்களில் ஒன்றை மீண்டும் வாழ சுழற்றுங்கள்.",
        credits_title: "காதல் வரவுகள்",
        credits_desc: "எனக்கு எல்லாவற்றிற்கும் நன்றி. ஒவ்வொரு ஆண்டும் இன்னும் எனக்கு முக்கியமானது.",
        years: "ஆண்டுகள்",
        months: "மாதங்கள்",
        days: "நாட்கள்",
        hours: "மணிநேரம்",
        minutes: "நிமிடங்கள்",
        seconds: "நொடிகள்",
        loyola_days: "லயோலா நாட்கள்",
        ego_title: "1000/100 ஈகோ",
        ego_desc: "எல்லாம் தொடங்கிய இடம்... உலகின் முன்னே இரண்டு பிடிவாத இதயங்கள்.",
        bus_chase: "பெரிய பேருந்து வேட்டை",
        bus_desc: "ஆன்சியைப் பார்க்க ஜியோ கல்லூரி பேருந்தைத் துரத்தினார் 🚌💨",
        panagudi_wait: "பணகுடி மாலைகள்",
        panagudi_desc: "ஒவ்வொரு நாளும் பேருந்து நிறுத்தத்தில் அவளுக்காகக் காத்திருக்கிறார்.",
        insta_handle: "Teddie queen 🧸",
        blood_art_title: "இரத்தக் கலை",
        blood_art_desc: "உன் மீதான என் காதலை வெளிப்படுத்த என் ஆன்மாவிலிருந்து வரையப்பட்ட ஒரு இதயம்.",
        cta_cube: "நமது தோட்டத்தை ஆராயுங்கள்",
        cta_reasons: "நமது தோட்டத்தை ஆராயுங்கள்",
        cta_garden: "நமது தாளத்தைக் கேளுங்கள்",
        cta_soundtrack: "நமது சாகசங்களைத் திட்டமிடுங்கள்",
        cta_adventure: "என் இதயத்திற்காக விளையாடுங்கள்",
        cta_hearts: "நமது நேர ஓட்டத்தைப் பாருங்கள்",
        cta_ticker: "என் கடிதங்களைத் திறங்கள்",
        cta_letters: "இந்த நினைவுகளைப் பாதுகாக்கவும்",
        cta_capsule: "நட்சத்திரங்களைப் பாருங்கள்",
        cta_starmap: "உலகளாவிய கட்டியணைப்பை அனுப்பவும்",
        cta_hug: "நமது கவிதையைப் படியுங்கள்",
        cta_poetry: "உருவங்களைச் சந்திக்கவும்",
        poetry_tap_hint: "உள்ளே எழுதப்பட்டதை பார்க்க ஒரு இதயத்தைத் தட்டவும்",
        poetry_teaser_prefix: "ஒரு நினைவு",
        poetry_more_waiting: "இன்னும் காத்திருக்கிறது, நீ மீண்டும் வரும்போது.",
        cta_characters: "நமது மைல்கற்களைப் பாருங்கள்",
        cta_milestones: "நமது ஆண்டுவிழாவை மீண்டும் வாழுங்கள்",
        cta_anniversary: "சிறப்புத் தேதியைத் திட்டமிடுங்கள்",
        cta_dategen: "பெரிய இறுதிப் பகுதிக்கு",
    },
};
