export const reasonsList = {
    en: [
        "Your smile lights up my whole world.",
        "The way you handle my 1000/100 ego with love.",
        "How you make 2,845 KM feel like zero.",
        "Your kindness towards everyone you meet.",
        "The way you say my name (Driver).",
        "Our shared dreams for a beautiful future.",
        "The strength you've shown in our 5-year journey.",
        "You are my best friend and my soulmate.",
        "How you believe in my dreams as much as I do.",
        "Your laugh is my favorite song.",
        "The way you look at me even through a screen.",
        "How you wait for my calls no matter the time difference.",
        "Your support during my long days in Dubai.",
        "The way you love your family.",
        "Your stubbornness that matches mine perfectly.",
        "How you make every day feel like Valentine's day.",
        "The way you care for the smallest things.",
        "Your patience when I'm being difficult.",
        "The way you inspire me to be a better person.",
        "Because you are the 'Teddie queen' of my heart.",
        "The memory of chasing your college bus (100% worth it).",
        "How you finally ignored your ego and chose us.",
        "Your bravery in choosing a long-distance life for now.",
        "The way you trust me with your deepest secrets.",
        "Because you are my 'Muhh' and my forever.",
        "The way you handle our distance with such grace.",
        "How you make me feel like the luckiest man alive.",
        "Your prayers for us and our future.",
        "The way you celebrate my small wins in my career.",
        "Because you are your Driver's greatest inspiration.",
        "The way you remember the smallest details about our start.",
        "How you look in a traditional saree in Tirunelveli.",
        "The way you handle the heat of the world with a cool heart.",
        "Because our first kiss was at the most unexpected place.",
        "The way you put the ring on my hand and gave me hope.",
        "How you lean on my shoulder in the park.",
        "The way we share silence without it being awkward.",
        "Because you are my priority, always and forever.",
        "The way you say 'I love you' and mean it every time.",
        "How you've grown alongside me over these 5 years.",
        "Your voice is the peace I find after a chaotic day.",
        "The way you fight for us when things get hard.",
        "How you make my home feel like home, even from afar.",
        "Your eyes reflect the stars I see in Dubai.",
        "Because you are the maple leaf in my life's garden.",
        "The way you've changed my life for the better.",
        "How you accept my flaws and love me anyway.",
        "Your ambition and how hard you work.",
        "The way you surprise me with your kindness.",
        "Because you are the piece of art that completed my soul.",
        "The way you hold my hand (even if only in memories for now).",
        "How you make me laugh when I want to be serious.",
        "Your intelligence and how you see the world.",
        "Because you are the rhythm of my heart's soundtrack.",
        "The way you care for your sisters and parents.",
        "How you've remained constant in a changing world.",
        "Your faith in our reunion.",
        "The way you handle my protective nature.",
        "Because you are the only one who truly gets me.",
        "How you've become the main character of my life.",
        "Your resilience through the ups and downs.",
        "The way you make the simplest moments special.",
        "How you challenge me to grow.",
        "Because you are the 'queen' in 'Teddie queen'.",
        "The way you look when you're thinking deeply.",
        "How you value our relationship over temporary things.",
        "Your loyalty is my greatest treasure.",
        "The way you've stood by me during my Dubai transitions.",
        "Because you are my peace in this busy world.",
        "How you make 5 years feel like just the first chapter.",
        "Your gentle touch (that I miss every day).",
        "The way you talk about our future home.",
        "Because you are the reason I work so hard.",
        "How you've integrated into my soul.",
        "Your sense of humor is perfectly aligned with mine.",
        "The way you handle my busy schedule with understanding.",
        "Because you are the heartbeat of my life.",
        "How you've taught me what real love is.",
        "Your sincerity in everything you do.",
        "The way you make Tirunelveli feel like the center of the world.",
        "Because our souls belong together.",
        "How you've kept every tiny gift I've given you.",
        "Your optimism when I feel cynical.",
        "The way you say 'Driver' with that specific tone.",
        "Because you are the best thing that ever happened to me.",
        "How you've survived the 'Bus Chase' days into forever.",
        "Your maturity in handling our life's complex dates.",
        "The way you look at the stars and think of me.",
        "Because you are my first and last thought every day.",
        "How you've made me a man with a poetic heart.",
        "Your gentleness towards animals and nature.",
        "The way you respect my parents and family.",
        "Because you've made me realize that distance is just a test.",
        "How you've passed every test our love has faced.",
        "Your beauty is both inside and out.",
        "The way you've made me believe in 'Forever'.",
        "Because you are you, and that is more than enough.",
        "How you've become my home, no matter where I am.",
        "Because I need to be with you till my last breath.",
        "Because you are my most priority, not the least."
    ],
    ta: [
        "உன் புன்னகை என் உலகம் முழுவதையும் ஒளிரச் செய்கிறது.",
        "எனது 1000/100 ஈகோவையும் அன்புடன் நீ கையாளும் விதம்.",
        "2,845 கிமீ தூரத்தை பூஜ்ஜியமாக உணர வைக்கும் விதம்.",
        "நீ சந்திக்கும் அனைவரிடமும் காட்டும் தயவு.",
        "என் பெயரை (டிரைவர்) நீ சொல்லும் விதம்.",
        "அழகான எதிர்காலத்திற்காக நாம் பகிரும் கனவுகள்.",
        "நமது 5 ஆண்டு பயணத்தில் நீ காட்டிய உறுதி.",
        "நீ என் சிறந்த நண்பன் மற்றும் என் ஆத்மார்த்தமானவள்.",
        "நான் என் கனவுகளை நம்புவதைப் போலவே நீயும் அவற்றை நம்புகிறாய்.",
        "உன் சிரிப்பு எனக்கு மிகவும் பிடித்த இசை.",
        "திரை வழியாகவும் நீ என்னை பார்க்கும் விதம்.",
        "நேர வித்தியாசம் இருந்தாலும் என் அழைப்புகளுக்காக நீ காத்திருக்கும் விதம்.",
        "துபாயில் என் கடினமான நாட்களில் உனது ஆதரவு.",
        "உன் குடும்பத்தை நீ நேசிக்கும் விதம்.",
        "என்னுடையதற்கு இணையாக இருக்கும் உனது பிடிவாதம்.",
        "ஒவ்வொரு நாளையும் காதலர் தினமாக உணர வைக்கும் விதம்.",
        "சிறிய விஷயங்களிலும் நீ காட்டும் அக்கறை.",
        "நான் கடினமாக இருக்கும்போது உனது பொறுமை.",
        "என்னை ஒரு சிறந்த மனிதனாக மாற்ற நீ தூண்டும் விதம்.",
        "ஏனென்றால் நீ என் இதயத்தின் 'Teddie queen'.",
        "உன் கல்லூரி பேருந்தைத் துரத்திய நினைவுகள் (100% மதிப்புடையது).",
        "உன் ஈகோவைக் கடந்து நமக்காக நீ தேர்ந்தெடுத்த விதம்.",
        "தூரத்து வாழ்க்கையைத் தேர்ந்தெடுத்த உனது துணிச்சல்.",
        "உன் ஆழமான ரகசியங்களை என்னிடம் நம்பி ஒப்படைக்கும் விதம்.",
        "ஏனென்றால் நீ என் 'முஹ்' மற்றும் என் என்றென்றும்.",
        "நமது தூரத்தை கனிவாக நீ கையாளும் விதம்.",
        "என்னை உலகின் அதிர்ஷ்டசாலி மனிதனாக உணர வைக்கும் விதம்.",
        "நமக்காகவும் நமது எதிர்காலத்திற்காகவும் உனது பிரார்த்தனைகள்.",
        "என் வாழ்க்கையின் சிறிய வெற்றிகளை நீ கொண்டாடும் விதம்.",
        "ஏனென்றால் நீ உன் டிரைவரின் மிகப்பெரிய உத்வேகம்.",
        "நமது தொடக்கத்தைப் பற்றிய சிறிய விவரங்களையும் நீ நினைவில் வைத்திருக்கும் விதம்.",
        "திருநெல்வேலியில் பாரம்பரிய சேலையில் நீ இருக்கும் அழகு.",
        "உலக வெப்பத்தைத் தணிக்கும் குளிர்ந்த இதயம் உன்னுடையது.",
        "ஏனென்றால் நமது முதல் முத்தம் எதிர்பாராத இடத்தில் அமைந்தது.",
        "என் கையில் மோதிரம் போட்டு எனக்கு நம்பிக்கை கொடுத்த விதம்.",
        "பூங்காவில் என் தோளில் நீ சாய்ந்து கொள்ளும் தருணம்.",
        "சங்கடம் ஏதுமின்றி நாம் மௌனத்தைப் பகிர்ந்து கொள்ளும் விதம்.",
        "ஏனென்றால் என் முன்னுரிமை நீயே, என்றும் எப்போதும்.",
        "ஒவ்வொரு முறையும் நீ 'ஐ லவ் யூ' சொல்லும் உண்மையான விதம்.",
        "இந்த 5 ஆண்டுகளில் என்னுடன் சேர்ந்து நீ வளர்ந்த விதம்.",
        "பரபரப்பான நாளுக்குப் பிறகு உன் குரல் எனக்குத் தரும் அமைதி.",
        "கடினமான நேரங்களில் நமக்காக நீ போராடும் விதம்.",
        "தூரத்திலிருந்து கொண்டு என் வீட்டை வீடாக உணர வைக்கும் விதம்.",
        "துபாயில் நான் பார்க்கும் நட்சத்திரங்களை உன் கண்கள் பிரதிபலிக்கின்றன.",
        "ஏனென்றால் நீ என் வாழ்க்கைத் தோட்டத்தின் மேப்பிள் இலை.",
        "என் வாழ்க்கையைச் சிறப்பானதாக நீ மாற்றிய விதம்.",
        "என் குறைகளை ஏற்றுக்கொண்டு என்னை நேசிக்கும் விதம்.",
        "உனது லட்சியமும் நீ உழைக்கும் விதமும்.",
        "உனது தயவால் நீ என்னை வியக்க வைக்கும் விதம்.",
        "ஏனென்றால் நீ என் ஆன்மாவைப் பூர்த்தி செய்த கலைப்படைப்பு.",
        "என் கையை நீ பிடிக்கும் விதம் (இப்போது நினைவுகளில் மட்டுமே இருந்தாலும்).",
        "நான் தீவிரமாக இருக்கும்போது என்னை சிரிக்க வைக்கும் விதம்.",
        "உன் புத்திசாலித்தனம் மற்றும் நீ உலகைப் பார்க்கும் விதம்.",
        "ஏனென்றால் நீ என் இதயத் துடிப்பின் இசை.",
        "உன் சகோதரிகள் மற்றும் பெற்றோரை நீ கவனித்துக்கொள்ளும் விதம்.",
        "மாறிவரும் உலகில் நீ மாறாமல் இருக்கும் விதம்.",
        "நமது மீண்டும் இணைதலில் உனக்குள்ள நம்பிக்கை.",
        "என் பாதுகாப்பான சுபாவத்தை நீ கையாளும் விதம்.",
        "ஏனென்றால் என்னை உண்மையிலேயே புரிந்துகொண்ட ஒரே நபர் நீதான்.",
        "எப்படியோ நீ என் வாழ்க்கையின் கதாநாயகியாக மாறிவிட்டாய்.",
        "ஏற்றத் தாழ்வுகளில் உனது மீள்தன்மை.",
        "எளிமையான தருணங்களையும் நீ சிறப்பானதாக மாற்றும் விதம்.",
        "என்னை வளர நீ சவால் விடுக்கும் விதம்.",
        "ஏனென்றால் 'Teddie queen' என்பதில் நீயே 'ராணி'.",
        "நீ ஆழமாகச் சிந்திக்கும் போது உன்னைப் பார்க்கும் அழகு.",
        "தற்காலிக விஷயங்களை விட நமது உறவை நீ மதிக்கும் விதம்.",
        "உனது விசுவாசம் என் மிகப்பெரிய செல்வம்.",
        "என் துபாய் மாற்றங்களின் போது என்னுடன் நின்ற விதம்.",
        "ஏனென்றால் இந்தத் திரண்ட உலகில் நீயே என் அமைதி.",
        "5 ஆண்டுகளை ஒரு தொடக்கமாக உணர வைக்கும் விதம்.",
        "உனது மென்மையான தீண்டல் (இதை நான் ஒவ்வொரு நாளும் இழக்கிறேன்).",
        "நமது எதிர்கால வீட்டைப் பற்றி நீ பேசும் விதம்.",
        "ஏனென்றால் நான் கடினமாக உழைப்பதற்குக் காரணமே நீதான்.",
        "என் ஆன்மாவுடன் நீ ஒன்றிவிட்ட விதம்.",
        "உனது நகைச்சுவை உணர்வு என்னுடன் சரியாகப் பொருந்துகிறது.",
        "என் பிஸியான நேரத்தை நீ புரிந்துகொள்ளும் விதம்.",
        "ஏனென்றால் நீ என் வாழ்க்கையின் இதயத்துடிப்பு.",
        "உண்மையான காதல் என்ன என்பதை நீ எனக்குக் கற்றுக்கொடுத்த விதம்.",
        "ஒவ்வொரு செயலிலும் உனது நேர்மை.",
        "திருநெல்வேலியை உலகின் மையமாக உணர வைக்கும் விதம்.",
        "ஏனென்றால் நமது ஆன்மாக்கள் ஒன்றுக்கொன்று சொந்தமானவை.",
        "நான் கொடுத்த ஒவ்வொரு சிறிய பரிசையும் நீ பாதுகாக்கும் விதம்.",
        "நான் விரக்தியாக இருக்கும்போது உனது நேர்மறை எண்ணம்.",
        "அந்தக் குறிப்பிட்ட தொனியில் நீ 'டிரைவர்' என்று சொல்லும் விதம்.",
        "ஏனென்றால் என் வாழ்க்கையில் நடந்த மிகச் சிறந்த விஷயம் நீதான்.",
        "பேருந்து துரத்தல் முதல் இன்று வரை நிலைத்திருக்கும் உனது அன்பு.",
        "நமது வாழ்க்கையின் கடினமான நேரங்களை நீ கையாளும் முதிர்ச்சி.",
        "நட்சத்திரங்களைப் பார்த்து என்னை நினைத்துப் பார்க்கும் விதம்.",
        "ஏனென்றால் ஒவ்வொரு நாளும் என் முதல் மற்றும் கடைசி நினைப்பு நீதான்.",
        "கவிதை உள்ளம் கொண்ட மனிதனாக என்னை மாற்றிய விதம்.",
        "விலங்குகள் மற்றும் இயற்கையின் மீதான உனது மென்மையான போக்கு.",
        "என் பெற்றோர் மற்றும் குடும்பத்தை நீ மதிக்கும் விதம்.",
        "தூரம் என்பது ஒரு சோதனை மட்டுமே என்பதை உணர வைத்த விதம்.",
        "காதலின் அனைத்து சோதனைகளையும் நீ வென்ற விதம்.",
        "இருந்தாலும் உன் அழகு உள்ளேயும் வெளியேயும் இருக்கிறது.",
        "என்றென்றும் (Forever) என்பதில் என்னை நம்ப வைத்த விதம்.",
        "ஏனென்றால் நீயே நீயாக இருக்கிறாய், அதுவே போதுமானது.",
        "நான் எங்கு இருந்தாலும் நீயே என் வீடாகிவிட்டாய்.",
        "ஏனென்றால் என் கடைசி மூச்சு வரை நான் உன்னுடன் இருக்க வேண்டும்.",
        "ஏனென்றால் நீயே என் முதல் முன்னுரிமை, கடைசி அல்ல."
    ]
};
